### PR TITLE
Allow to download images to assets

### PR DESCRIPTION
**Pull request by miry**
Command used
```
medup -u alrouen
```

Example file: `2018-07-10-hey-snips.md`

You can see the code is 

```markdown
![Photo by Rachel on Unsplash][image_ref_MCpyWG1tUEEwVUozbVlXN1hP]
```

But the picture isn't downloaded (and the file path should be something like `/assets/image_ref_MCpyWG1tUEEwVUozbVlXN1hP.ext`)

### CODE REVIEW

**Comment by clawfire** [comment]
❤

**Comment by miry** [comment]
@clawfire Released a new version v0.2.0

Now it is possible to have images in assets folder:

```shell
$ brew upgrade
$ medup -p smileinnovation --assets-images -d posts/smileinnovation
```

**Comment by clawfire** [comment]
Awesome 👍🏼 
Just saw a little error, 

Some pictures of some article is saved without extension and the markdown code is use the same filename (without extension) but the browser will not render it. 

Ex: `2018-07-10-hey-snips.md` 

```markdown
![Photo by Rachel on Unsplash](./assets/0*rXmmPA0UJ3mYW7XO)
```

Ex: `2018-05-15-smile-innovations-watch-1` is full of them

```markdown
![](./assets/0*GjKrDjzBwMyozeO7.)

![](./assets/0*UIYSEe6hEqeBsRz9.)

![](./assets/0*megKASgvlGTscplj.)
```

**Comment by miry** [comment]
@clawfire It is true. It depends how the image was created in medium. medup does not do any type detection for now base on file content.

**Comment by clawfire** [comment]
Oh ok. Thought the browser will just cry if we do so.

**Comment by miry** [comment]
@clawfire Thanks for reminder and I have fixed the problem in #37.

**Comment by clawfire** [comment]
> @clawfire Thanks for reminder and I have fixed the problem in #37.

That's awesome ❤ thanks for the great work

**Pull request merged**
